#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otomasyon.Fonksyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="otomasyon")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_STOK_GRUPLARI(TBL_STOK_GRUPLARI instance);
    partial void UpdateTBL_STOK_GRUPLARI(TBL_STOK_GRUPLARI instance);
    partial void DeleteTBL_STOK_GRUPLARI(TBL_STOK_GRUPLARI instance);
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::otomasyon.Properties.Settings.Default.otomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_STOK_GRUPLARI> TBL_STOK_GRUPLARIs
		{
			get
			{
				return this.GetTable<TBL_STOK_GRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLARs
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[TBL_STOK GRUPLARI]")]
	public partial class TBL_STOK_GRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _GRUPADİ;
		
		private string _GRUPKODU;
		
		private System.Nullable<int> _GRUPSAVEUSER;
		
		private System.Nullable<System.DateTime> _GRUPSAVEDATE;
		
		private System.Nullable<int> _GRUPEDİTUSER;
		
		private System.Nullable<System.DateTime> _GRUPEDİTDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnGRUPADİChanging(string value);
    partial void OnGRUPADİChanged();
    partial void OnGRUPKODUChanging(string value);
    partial void OnGRUPKODUChanged();
    partial void OnGRUPSAVEUSERChanging(System.Nullable<int> value);
    partial void OnGRUPSAVEUSERChanged();
    partial void OnGRUPSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPSAVEDATEChanged();
    partial void OnGRUPEDİTUSERChanging(System.Nullable<int> value);
    partial void OnGRUPEDİTUSERChanged();
    partial void OnGRUPEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnGRUPEDİTDATEChanged();
    #endregion
		
		public TBL_STOK_GRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPADİ", DbType="NChar(30)")]
		public string GRUPADİ
		{
			get
			{
				return this._GRUPADİ;
			}
			set
			{
				if ((this._GRUPADİ != value))
				{
					this.OnGRUPADİChanging(value);
					this.SendPropertyChanging();
					this._GRUPADİ = value;
					this.SendPropertyChanged("GRUPADİ");
					this.OnGRUPADİChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPKODU", DbType="NChar(30)")]
		public string GRUPKODU
		{
			get
			{
				return this._GRUPKODU;
			}
			set
			{
				if ((this._GRUPKODU != value))
				{
					this.OnGRUPKODUChanging(value);
					this.SendPropertyChanging();
					this._GRUPKODU = value;
					this.SendPropertyChanged("GRUPKODU");
					this.OnGRUPKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEUSER", DbType="Int")]
		public System.Nullable<int> GRUPSAVEUSER
		{
			get
			{
				return this._GRUPSAVEUSER;
			}
			set
			{
				if ((this._GRUPSAVEUSER != value))
				{
					this.OnGRUPSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEUSER = value;
					this.SendPropertyChanged("GRUPSAVEUSER");
					this.OnGRUPSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPSAVEDATE
		{
			get
			{
				return this._GRUPSAVEDATE;
			}
			set
			{
				if ((this._GRUPSAVEDATE != value))
				{
					this.OnGRUPSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPSAVEDATE = value;
					this.SendPropertyChanged("GRUPSAVEDATE");
					this.OnGRUPSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDİTUSER", DbType="Int")]
		public System.Nullable<int> GRUPEDİTUSER
		{
			get
			{
				return this._GRUPEDİTUSER;
			}
			set
			{
				if ((this._GRUPEDİTUSER != value))
				{
					this.OnGRUPEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDİTUSER = value;
					this.SendPropertyChanged("GRUPEDİTUSER");
					this.OnGRUPEDİTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRUPEDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> GRUPEDİTDATE
		{
			get
			{
				return this._GRUPEDİTDATE;
			}
			set
			{
				if ((this._GRUPEDİTDATE != value))
				{
					this.OnGRUPEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._GRUPEDİTDATE = value;
					this.SendPropertyChanged("GRUPEDİTDATE");
					this.OnGRUPEDİTDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _BARKOD;
		
		private string _STOKKODU;
		
		private string _STOKADİ;
		
		private string _STOKBİRİM;
		
		private System.Nullable<decimal> _STOKALİSFİYAT;
		
		private System.Nullable<decimal> _STOKSATİSFİYAT;
		
		private System.Nullable<decimal> _STOKALİSKDV;
		
		private System.Nullable<decimal> _STOKSATİSKDV;
		
		private System.Nullable<int> _STOKGRUPID;
		
		private System.Data.Linq.Binary _STOKRESİM;
		
		private System.Nullable<int> _STOKSAVEUSER;
		
		private System.Nullable<System.DateTime> _STOKSAVEDATE;
		
		private System.Nullable<int> _STOKEDİTUSER;
		
		private System.Nullable<System.DateTime> _STOKEDİTDATE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBARKODChanging(string value);
    partial void OnBARKODChanged();
    partial void OnSTOKKODUChanging(string value);
    partial void OnSTOKKODUChanged();
    partial void OnSTOKADİChanging(string value);
    partial void OnSTOKADİChanged();
    partial void OnSTOKBİRİMChanging(string value);
    partial void OnSTOKBİRİMChanged();
    partial void OnSTOKALİSFİYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKALİSFİYATChanged();
    partial void OnSTOKSATİSFİYATChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATİSFİYATChanged();
    partial void OnSTOKALİSKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKALİSKDVChanged();
    partial void OnSTOKSATİSKDVChanging(System.Nullable<decimal> value);
    partial void OnSTOKSATİSKDVChanged();
    partial void OnSTOKGRUPIDChanging(System.Nullable<int> value);
    partial void OnSTOKGRUPIDChanged();
    partial void OnSTOKRESİMChanging(System.Data.Linq.Binary value);
    partial void OnSTOKRESİMChanged();
    partial void OnSTOKSAVEUSERChanging(System.Nullable<int> value);
    partial void OnSTOKSAVEUSERChanged();
    partial void OnSTOKSAVEDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKSAVEDATEChanged();
    partial void OnSTOKEDİTUSERChanging(System.Nullable<int> value);
    partial void OnSTOKEDİTUSERChanged();
    partial void OnSTOKEDİTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSTOKEDİTDATEChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BARKOD", DbType="NVarChar(30)")]
		public string BARKOD
		{
			get
			{
				return this._BARKOD;
			}
			set
			{
				if ((this._BARKOD != value))
				{
					this.OnBARKODChanging(value);
					this.SendPropertyChanging();
					this._BARKOD = value;
					this.SendPropertyChanged("BARKOD");
					this.OnBARKODChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKKODU", DbType="NChar(20)")]
		public string STOKKODU
		{
			get
			{
				return this._STOKKODU;
			}
			set
			{
				if ((this._STOKKODU != value))
				{
					this.OnSTOKKODUChanging(value);
					this.SendPropertyChanging();
					this._STOKKODU = value;
					this.SendPropertyChanged("STOKKODU");
					this.OnSTOKKODUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADİ", DbType="NChar(50)")]
		public string STOKADİ
		{
			get
			{
				return this._STOKADİ;
			}
			set
			{
				if ((this._STOKADİ != value))
				{
					this.OnSTOKADİChanging(value);
					this.SendPropertyChanging();
					this._STOKADİ = value;
					this.SendPropertyChanged("STOKADİ");
					this.OnSTOKADİChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKBİRİM", DbType="NChar(15)")]
		public string STOKBİRİM
		{
			get
			{
				return this._STOKBİRİM;
			}
			set
			{
				if ((this._STOKBİRİM != value))
				{
					this.OnSTOKBİRİMChanging(value);
					this.SendPropertyChanging();
					this._STOKBİRİM = value;
					this.SendPropertyChanged("STOKBİRİM");
					this.OnSTOKBİRİMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALİSFİYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALİSFİYAT
		{
			get
			{
				return this._STOKALİSFİYAT;
			}
			set
			{
				if ((this._STOKALİSFİYAT != value))
				{
					this.OnSTOKALİSFİYATChanging(value);
					this.SendPropertyChanging();
					this._STOKALİSFİYAT = value;
					this.SendPropertyChanged("STOKALİSFİYAT");
					this.OnSTOKALİSFİYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATİSFİYAT", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATİSFİYAT
		{
			get
			{
				return this._STOKSATİSFİYAT;
			}
			set
			{
				if ((this._STOKSATİSFİYAT != value))
				{
					this.OnSTOKSATİSFİYATChanging(value);
					this.SendPropertyChanging();
					this._STOKSATİSFİYAT = value;
					this.SendPropertyChanged("STOKSATİSFİYAT");
					this.OnSTOKSATİSFİYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKALİSKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKALİSKDV
		{
			get
			{
				return this._STOKALİSKDV;
			}
			set
			{
				if ((this._STOKALİSKDV != value))
				{
					this.OnSTOKALİSKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKALİSKDV = value;
					this.SendPropertyChanged("STOKALİSKDV");
					this.OnSTOKALİSKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSATİSKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> STOKSATİSKDV
		{
			get
			{
				return this._STOKSATİSKDV;
			}
			set
			{
				if ((this._STOKSATİSKDV != value))
				{
					this.OnSTOKSATİSKDVChanging(value);
					this.SendPropertyChanging();
					this._STOKSATİSKDV = value;
					this.SendPropertyChanged("STOKSATİSKDV");
					this.OnSTOKSATİSKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKGRUPID", DbType="Int")]
		public System.Nullable<int> STOKGRUPID
		{
			get
			{
				return this._STOKGRUPID;
			}
			set
			{
				if ((this._STOKGRUPID != value))
				{
					this.OnSTOKGRUPIDChanging(value);
					this.SendPropertyChanging();
					this._STOKGRUPID = value;
					this.SendPropertyChanged("STOKGRUPID");
					this.OnSTOKGRUPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKRESİM", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary STOKRESİM
		{
			get
			{
				return this._STOKRESİM;
			}
			set
			{
				if ((this._STOKRESİM != value))
				{
					this.OnSTOKRESİMChanging(value);
					this.SendPropertyChanging();
					this._STOKRESİM = value;
					this.SendPropertyChanged("STOKRESİM");
					this.OnSTOKRESİMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEUSER", DbType="Int")]
		public System.Nullable<int> STOKSAVEUSER
		{
			get
			{
				return this._STOKSAVEUSER;
			}
			set
			{
				if ((this._STOKSAVEUSER != value))
				{
					this.OnSTOKSAVEUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEUSER = value;
					this.SendPropertyChanged("STOKSAVEUSER");
					this.OnSTOKSAVEUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKSAVEDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKSAVEDATE
		{
			get
			{
				return this._STOKSAVEDATE;
			}
			set
			{
				if ((this._STOKSAVEDATE != value))
				{
					this.OnSTOKSAVEDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKSAVEDATE = value;
					this.SendPropertyChanged("STOKSAVEDATE");
					this.OnSTOKSAVEDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDİTUSER", DbType="Int")]
		public System.Nullable<int> STOKEDİTUSER
		{
			get
			{
				return this._STOKEDİTUSER;
			}
			set
			{
				if ((this._STOKEDİTUSER != value))
				{
					this.OnSTOKEDİTUSERChanging(value);
					this.SendPropertyChanging();
					this._STOKEDİTUSER = value;
					this.SendPropertyChanged("STOKEDİTUSER");
					this.OnSTOKEDİTUSERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKEDİTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> STOKEDİTDATE
		{
			get
			{
				return this._STOKEDİTDATE;
			}
			set
			{
				if ((this._STOKEDİTDATE != value))
				{
					this.OnSTOKEDİTDATEChanging(value);
					this.SendPropertyChanging();
					this._STOKEDİTDATE = value;
					this.SendPropertyChanged("STOKEDİTDATE");
					this.OnSTOKEDİTDATEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
